// File generated by FlutterFire CLI.
// ignore_for_file: type=lint

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }

    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;

      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios.',
        );

      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos.',
        );

      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows.',
        );

      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux.',
        );

      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCKZhqYFVlYV8844vzTm2X_1APvhcfmUdE',
    appId: '1:646747466729:web:ccd46b1455b9a6b525f978',
    messagingSenderId: '646747466729',
    projectId: 'taller2-flutterfirebase',
    authDomain: 'taller2-flutterfirebase.firebaseapp.com',
    databaseURL:
        'https://taller2-flutterfirebase-default-rtdb.firebaseio.com',
    storageBucket: 'taller2-flutterfirebase.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCxIZ_Up1bXLG6o6669Y68Csc2d7XlNVIs',
    appId: '1:646747466729:android:6f1b6f34462211e825f978',
    messagingSenderId: '646747466729',
    projectId: 'taller2-flutterfirebase',
    databaseURL:
        'https://taller2-flutterfirebase-default-rtdb.firebaseio.com',
    storageBucket: 'taller2-flutterfirebase.firebasestorage.app',
  );
}

